<a href="https://colab.research.google.com/github/Prakhar021-hub/pytorch-learnings/blob/main/pytorch_learnngs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

GPU is not available


Creating a **tensor**

In [4]:
## using empty
torch.empty(3,4)

tensor([[-3.0234e-25,  4.3454e-41, -3.0183e-25,  4.3454e-41],
        [-3.0184e-25,  4.3454e-41, -3.0214e-25,  4.3454e-41],
        [-3.0234e-25,  4.3454e-41, -3.0234e-25,  4.3454e-41]])

In [5]:
## using zeros
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
## using random
torch.rand(3,4)

tensor([[0.2467, 0.3442, 0.9041, 0.4021],
        [0.0470, 0.4131, 0.0970, 0.7832],
        [0.9476, 0.5488, 0.0935, 0.5170]])

In [7]:
torch.rand(3,4,5,6)

tensor([[[[0.9708, 0.3676, 0.4614, 0.5115, 0.3371, 0.2903],
          [0.2907, 0.1045, 0.3432, 0.4472, 0.1373, 0.7352],
          [0.0129, 0.0567, 0.2940, 0.5387, 0.8275, 0.6254],
          [0.2944, 0.2804, 0.0837, 0.8410, 0.8744, 0.2619],
          [0.8644, 0.6078, 0.3846, 0.2917, 0.9842, 0.6409]],

         [[0.1020, 0.0798, 0.3810, 0.8620, 0.9722, 0.9226],
          [0.5533, 0.8959, 0.2902, 0.7685, 0.3062, 0.4728],
          [0.5030, 0.7875, 0.8731, 0.0925, 0.4747, 0.0362],
          [0.4206, 0.2614, 0.8990, 0.5132, 0.3591, 0.0017],
          [0.6979, 0.3172, 0.2645, 0.6103, 0.5944, 0.3971]],

         [[0.1091, 0.9839, 0.9777, 0.5099, 0.9133, 0.6284],
          [0.3637, 0.8577, 0.8872, 0.1399, 0.2347, 0.1124],
          [0.6231, 0.6025, 0.8553, 0.5509, 0.8022, 0.0264],
          [0.5774, 0.7039, 0.2592, 0.4926, 0.2493, 0.7647],
          [0.4733, 0.8931, 0.2265, 0.3398, 0.7568, 0.5740]],

         [[0.0417, 0.3815, 0.5358, 0.4171, 0.5039, 0.5675],
          [0.2897, 0.2792, 0.8375,

In [8]:
## rand with seed value
torch.manual_seed(2)
torch.rand(3,4)

tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

In [9]:
## custom tensors using tensor
torch.tensor([[1,2,3,4], [1,4,6,2], [2,6,3,9]])

tensor([[1, 2, 3, 4],
        [1, 4, 6, 2],
        [2, 6, 3, 9]])

In [10]:
## other  ways to create

## arange
print(torch.arange(0,10))

## linspace
print(torch.linspace(0,20,20))

##using eye
print(torch.eye(5))

##using full
torch.full((3,4), 5)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0.0000,  1.0526,  2.1053,  3.1579,  4.2105,  5.2632,  6.3158,  7.3684,
         8.4211,  9.4737, 10.5263, 11.5789, 12.6316, 13.6842, 14.7368, 15.7895,
        16.8421, 17.8947, 18.9474, 20.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

##tensors shape


In [11]:
x = torch.tensor([[2,3,4], [1,7,9]])
x

tensor([[2, 3, 4],
        [1, 7, 9]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
## when you need to create a same shaped tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [17]:
## data types

In [18]:
x.dtype

torch.int64

In [19]:
## defining data type while initialising

torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
## we can also change the data type of a predefine variable

x.to(torch.float32)

tensor([[2., 3., 4.],
        [1., 7., 9.]])

## mathematical operations on tensors


In [22]:
## 1. scalar operation

torch.manual_seed(3)
y = torch.rand(2,2)
y

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270]])

In [23]:
## addition
print(y + 3)

## substractions
print(y-1)

## multiplication
print(y*2)

## division
print(y/2)

## power
print(y**2)


tensor([[3.0043, 3.1056],
        [3.2858, 3.0270]])
tensor([[-0.9957, -0.8944],
        [-0.7142, -0.9730]])
tensor([[0.0085, 0.2111],
        [0.5717, 0.0539]])
tensor([[0.0021, 0.0528],
        [0.1429, 0.0135]])
tensor([[1.8178e-05, 1.1145e-02],
        [8.1706e-02, 7.2656e-04]])


### performing mathematical operations/element wise operations on two identical tensor

In [24]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)

tensor([[0.4716, 0.0601],
        [0.7719, 0.7437]])
tensor([[0.5944, 0.8879],
        [0.4510, 0.7995]])


In [25]:
## addition
print(a + b )

## substraction
print(a-b)

## multiplication
print(a*b)

## division
print(a/b)

tensor([[1.0660, 0.9480],
        [1.2229, 1.5432]])
tensor([[-0.1228, -0.8277],
        [ 0.3208, -0.0558]])
tensor([[0.2803, 0.0534],
        [0.3481, 0.5946]])
tensor([[0.7934, 0.0677],
        [1.7113, 0.9302]])


In [26]:
## reduction operation

c = torch.randint(size = (3,3), low = 1, high = 5)
c

tensor([[2, 2, 3],
        [2, 4, 3],
        [1, 1, 1]])

In [27]:
## sum
print(torch.sum(c))

## sum along column
print(torch.sum(c, axis = 0))

## sum along row
print(torch.sum(c, axis = 1))

tensor(19)
tensor([5, 7, 7])
tensor([7, 9, 3])


In [28]:
# mean
print(torch.mean(c, dtype = torch.float32))

## mean along colomn
print(torch.mean(c, axis = 0, dtype = torch.float32))

## mean along row
print(torch.mean(c, axis = 1, dtype = torch.float32))


tensor(2.1111)
tensor([1.6667, 2.3333, 2.3333])
tensor([2.3333, 3.0000, 1.0000])


In [29]:
## median
print(torch.median(c))

tensor(2)


In [30]:
## min / max

print(torch.min(c))
print(torch.max(c))

tensor(1)
tensor(4)


In [31]:
## product
torch.prod(c)

tensor(288)

In [32]:
## standard deviation
torch.std(c.float())

tensor(1.0541)

In [33]:
## variance
torch.var(c.float())

tensor(1.1111)

## matrix operations

In [34]:
g = torch.randint(size = (2,3), low = 2, high = 10)
h = torch.randint(size = (2,3), low = 2, high = 10)
print(g)
print(h)

tensor([[7, 9, 8],
        [2, 4, 3]])
tensor([[4, 8, 4],
        [4, 9, 6]])


In [35]:
## matrix multiplication
print(torch.matmul(g, h.T))

tensor([[132, 157],
        [ 52,  62]])


In [38]:
## dot product
print(torch.tensordot(g, h.T, dims = 1))

tensor([[132, 157],
        [ 52,  62]])


In [45]:
## vector dot products
vector1 = torch.tensor([2,4])
vector2 = torch.tensor([3,7])
print(vector1)
print(vector2)

print(torch.dot(vector1, vector2))

tensor([2, 4])
tensor([3, 7])
tensor(34)
